### PR TITLE
Update itemdat.cpp

### PR DESCRIPTION
**Pull request by Captain-Barge**
Changed `iMinMLvl` for some items from -1 to 255 to avoid an unsigned integer issue.

Following [AJenbo](https://github.com/AJenbo)'s advice the code compiled successfully on Linux with this change. Resolves issue [12](https://github.com/SoundChaser83/devilutionx-apocrypha/issues/12).

### CODE REVIEW

**Comment by AJenbo** [comment]
-1 was probably set to try and have them never generated, but the value range is only 0-255 so -1 is undefined behavior. But the hex for -1 0xFF which is the same as for 255 so likely compiler that did not error on this would have used that value.

The only real alternative is setting it to 0, but I don't think that would give the desired result and probably breaks compared to previous versions of the mod.

**Comment by SoundChaser83** [comment]
Thanks for the help, everybody! This looks great to me, I just didn't want those items to drop. Setting to 255 should serve the same purpose, I assume.

**Comment by AJenbo** [comment]
You could also set the drop value to never (it's an enum in one of the first columns)

**Comment by AJenbo** [comment]
iMinMLvl is probably needed if you also do not want it in shops

**Comment by SoundChaser83** [comment]
Yeah, I didn't want those items to show up at all, neither from monster loot nor from shops.

**Pull request merged**
